[general]
output-filename = "/home/ruben/Pictures/Screenshots/screenshot-%Y-%m-%d_%H:%M:%S.png"
no-window-decoration = true

# Font to use for text annotations
[font]
family = "Roboto"
style = "Bold"


# Custom colours for the colour palette
[color-palette]
# These will be shown in the toolbar for quick selection
palette = [
    "#00ffff",
    "#a52a2a",
    "#dc143c",
    "#ff1493",
    "#ffd700",
    "#008000",
]

# These will be available in the color picker as presets
# Leave empty to use GTK's default
custom = [
    "#00ffff",
    "#a52a2a",
    "#dc143c",
    "#ff1493",
    "#ffd700",
    "#008000",
]