[preferred]
default=gnome;gtk;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
org.freedesktop.impl.portal.Secret=gnome-keyring;

# org.freedesktop.impl.portal.FileChooser=kde

# Usa gnome para capturas y pantallas
# org.freedesktop.impl.portal.ScreenCast=gnome
# org.freedesktop.impl.portal.Screenshot=gnome

# Que las apps (especialmente Electron como Logseq/Zotero)
# le pregunten a GNOME por el tema oscuro/claro
#org.freedesktop.impl.portal.Settings=gnome;gtk;

# Usa KDE para el resto (esto ayuda a Dolphin con KWallet)
# default=kde
