[preferred]
# Usa gnome para capturas y pantallas
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome
# Usa KDE para el resto (esto ayuda a Dolphin con KWallet)
default=kde