.config/niri/input.kdl
.config/niri/output.kdl
.config/niri/user.kdl
.config/niri/workspaces.kdl
.config/autostart/picom.desktop
.config/satty/config.toml
.config/qtile/config.py
.config/qtile/scripts/autostart.sh
.config/autostart/variety.desktop
