.config/mimeapps.list
.config/niri
.config/qtile/config.py
.config/qtile/settings
.config/rofi/config.rasi
.config/satty/config.toml
.config/starship.toml
.config/sway
.config/swayidle/config
.config/swaylock
.config/swaync
.config/user-dirs.dirs
.config/user-dirs.locale
.config/variety/variety.conf
.config/xsettingsd/xsettingsd.conf
