.config/gtk-3.0/bookmarks
.config/kitty/colors.conf
.config/kitty/current-theme.conf
.config/niri/config.kdl
.config/niri/screenshot_swappy.sh
.config/niri/waybar.sh
.config/niri/waybar/config.jsonc
.config/niri/waybar/config2.jsonc
.config/niri/waybar/style.css
.config/niri/waybar/style2.css
.config/niriswitcher/config.toml
.config/niriswitcher/style.css
.config/noctalia/settings.json
.config/satty/config.toml
.config/swayidle/config
