cursor #f8ddd0
cursor_text_color #dbc2b4

foreground            #f8ddd0
background            #1d1009
selection_foreground  #462a09
selection_background  #ecbe91
url_color             #ffb68a

color0   #1d1009
color1   #ff7972
color2   #96ff7f
color3   #ffe572
color4   #f29f6c
color5   #763812
color6   #ffb68a
color7   #fff5ef
color8   #a59e99
color9   #ffa39f
color10  #b5ffa5
color11  #ffefa5
color12  #ffc09b
color13  #ffcbad
color14  #ffdeca
color15  #fffbf8
