#!/bin/bash

WP=$1
cp "$WP" ~/wallpaper/default.jpg
dms ipc call wallpaper set "$WP"
chmod 644 "$WP"
sleep 1
gsettings set org.gnome.desktop.interface gtk-theme 'Matcha-dark-sea'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface cursor-theme 'oreo_teal_cursors'
gsettings set org.gnome.desktop.interface font-name 'Fira Sans 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'FiraCode Nerd Font Mono Regular 12'
dms ipc theme dark
