#!/bin/bash

WP=$1
cp "$WP" ~/wallpaper/default.jpg
dms ipc call wallpaper set "$WP"
chmod 644 "$WP"
sleep 1
gsettings set org.gnome.desktop.interface gtk-theme 'Matcha-dark-sea'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface cursor-theme 'oreo_teal_cursors'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
gsettings set org.gnome.desktop.interface font-name 'Fira Sans 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'FiraCode Nerd Font Mono Regular 12'
dms ipc theme dark
kwriteconfig6 --file kdeglobals --group General --key ColorScheme 'DankMatugenDark'
kwriteconfig6 --file kdeglobals --group General --key font 'Fira Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
kwriteconfig6 --file kdeglobals --group General --key fixed 'FiraCode Nerd Font Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
kwriteconfig6 --file kdeglobals --group General --key menuFont 'Fira Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
kwriteconfig6 --file kdeglobals --group General --key toolBarFont 'Fira Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
kwriteconfig6 --file kdeglobals --group Icons --key Theme 'Papirus-Dark'
sed -i 's|^color_scheme_path=.*|color_scheme_path=/home/ruben/.local/share/color-schemes/DankMatugen.colors|' ~/.config/qt5ct/qt5ct.conf
sed -i 's|^icon_theme=.*|icon_theme=Papirus-Dark|' ~/.config/qt5ct/qt5ct.conf
sed -i 's|^fixed=.*|fixed="FiraCode Nerd Font Mono,12,-1,5,50,0,0,0,0,0"|' ~/.config/qt5ct/qt5ct.conf
sed -i 's|^general=.*|general="Fira Sans,11,-1,5,50,0,0,0,0,0"|' ~/.config/qt5ct/qt5ct.conf
sed -i 's|^color_scheme_path=.*|color_scheme_path=/home/ruben/.local/share/color-schemes/DankMatugen.colors|' ~/.config/qt6ct/qt6ct.conf
sed -i 's|^icon_theme=.*|icon_theme=Papirus-Dark|' ~/.config/qt6ct/qt6ct.conf
sed -i 's|^fixed=.*|fixed="FiraCode Nerd Font Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"|' ~/.config/qt6ct/qt6ct.conf
sed -i 's|^general=.*|general="Fira Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"|' ~/.config/qt6ct/qt6ct.conf
